version: "3.3"
name: expenses-app

services:
  postgresdb:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ${ROOT_DIR}/app/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    depends_on:
      - postgresdb
    ports:
      - 8080:8080
    environment:
      - PG_HOST=postgresdb
      - APP_ID=expenses-app-s

volumes:
  db:
    driver: local
